application: suxford-hrd
version: 2
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /grabtweets
  script: main.app
  login: admin

- url: /grabanalysis
  script: main.app
  login: admin

- url: /analysishistory
  script: main.app
  login: admin

- url: /tidyup
  script: main.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
