application: suxford
version: 2
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /grabtweets
  script: main.py
  login: admin

- url: /grabanalysis
  script: main.py
  login: admin

- url: /analysishandler
  script: main.py
  login: admin

- url: .*
  script: main.py

